export const fixTags: Record<string, string> = {
    "8": "BeginString",
    "9": "BodyLength",
    "35": "MsgType",
    "34": "MsgSeqNum",
    "49": "SenderCompID",
    "56": "TargetCompID",
    "52": "SendingTime",
    "10": "CheckSum",
    "11": "ClOrdID",
    "1": "Account",
    "21": "HandlInst",
    "55": "Symbol",
    "54": "Side",
    "60": "TransactTime",
    "38": "OrderQty",
    "40": "OrdType",
    "44": "Price",
    "150": "ExecType",
    "39": "OrdStatus",
    "14": "CumQty",
    "6": "AvgPx",
    "32": "LastQty",
    "31": "LastPx",
    "151": "LeavesQty",
    "37": "OrderID",
    "17": "ExecID",
    "58": "Text",
    "59": "TimeInForce",
    "167": "SecurityType",
    "41": "OrigClOrdID",
    "20": "ExecTransType",
    "30": "LastMkt",
    "128": "DeliverToCompID",
    "129": "DeliverToSubID",
    "115": "OnBehalfOfCompID",
    "116": "OnBehalfOfSubID",
    "76": "ExecBroker",
    "57": "TargetSubID",
    "50": "SenderSubID",
    "432": "ExpireDate",
    "207": "SecurityExchange",
};

export const msgTypes: Record<string, string> = {
    "D": "New Order - Single",
    "8": "Execution Report",
    "A": "Logon",
    "0": "Heartbeat",
    "F": "Order Cancel Request",
    "G": "Order Cancel/Replace Request",
    "3": "Reject",
    "h": "Trading Session Status",
    "4": "Sequence Reset",
    "5": "Logout",
};
